const sampleUsers = [
  {
    username: 'hrittik_india',
    name: 'Hrittik Maurya',
    photo: 'https://i.pravatar.cc/300?img=12',
    email: 'mmhrittik@gmail.com',
    followers: 55,
    followings: 61,
    bio: 'B.Tech student | Web development | C++',
    posts: 0,
  },
  {
    username: 'arjun_dev',
    name: 'Arjun Sharma',
    photo: 'https://i.pravatar.cc/300?img=11',
    email: 'arjun.sharma@example.com',
    followers: 128,
    followings: 94,
    bio: 'Frontend developer | Coffee | Open source',
    posts: 14,
  },
  {
    username: 'priya_codes',
    name: 'Priya Verma',
    photo: 'https://i.pravatar.cc/300?img=5',
    email: 'priya.verma@example.com',
    followers: 342,
    followings: 156,
    bio: 'Computer science student | JavaScript learner',
    posts: 27,
  },
  {
    username: 'rahul_tech',
    name: 'Rahul Singh',
    photo: 'https://i.pravatar.cc/300?img=13',
    email: 'rahul.singh@example.com',
    followers: 89,
    followings: 120,
    bio: 'Developer | Gamer | Tech enthusiast',
    posts: 9,
  },
  {
    username: 'ananya_creates',
    name: 'Ananya Gupta',
    photo: 'https://i.pravatar.cc/300?img=47',
    email: 'ananya.gupta@example.com',
    followers: 512,
    followings: 210,
    bio: 'Designer | Creator | Photography',
    posts: 36,
  },
  {
    username: 'vikas_cpp',
    name: 'Vikas Yadav',
    photo: 'https://i.pravatar.cc/300?img=68',
    email: 'vikas.yadav@example.com',
    followers: 76,
    followings: 83,
    bio: 'C++ | DSA | Competitive programming',
    posts: 18,
  },
  {
    username: 'neha_tech',
    name: 'Neha Mishra',
    photo: 'https://i.pravatar.cc/300?img=44',
    email: 'neha.mishra@example.com',
    followers: 221,
    followings: 178,
    bio: 'Web developer | Learning every day',
    posts: 22,
  },
  {
    username: 'rohit_builds',
    name: 'Rohit Kumar',
    photo: 'https://i.pravatar.cc/300?img=14',
    email: 'rohit.kumar@example.com',
    followers: 167,
    followings: 132,
    bio: 'Building things with JavaScript',
    posts: 31,
  },
  {
    username: 'simran_techie',
    name: 'Simran Kaur',
    photo: 'https://i.pravatar.cc/300?img=49',
    email: 'simran.kaur@example.com',
    followers: 403,
    followings: 275,
    bio: 'Tech enthusiast | Books | Travel',
    posts: 42,
  },
  {
    username: 'aman_sings',
    name: 'Aman Verma',
    photo: 'https://i.pravatar.cc/300?img=8',
    email: 'aman.verma@example.com',
    followers: 289,
    followings: 104,
    bio: 'Singer | Student | Music lover',
    posts: 25,
  },
  {
    username: 'devansh_js',
    name: 'Devansh Pandey',
    photo: 'https://i.pravatar.cc/300?img=15',
    email: 'devansh.pandey@example.com',
    followers: 114,
    followings: 97,
    bio: 'JavaScript developer | Node.js',
    posts: 16,
  },
  {
    username: 'riya_designs',
    name: 'Riya Tiwari',
    photo: 'https://i.pravatar.cc/300?img=32',
    email: 'riya.tiwari@example.com',
    followers: 634,
    followings: 189,
    bio: 'UI designer | Creative mind',
    posts: 51,
  },
  {
    username: 'karan_dsa',
    name: 'Karan Mehta',
    photo: 'https://i.pravatar.cc/300?img=53',
    email: 'karan.mehta@example.com',
    followers: 198,
    followings: 143,
    bio: 'DSA | C++ | Software engineering',
    posts: 29,
  },
  {
    username: 'isha_journey',
    name: 'Isha Srivastava',
    photo: 'https://i.pravatar.cc/300?img=45',
    email: 'isha.srivastava@example.com',
    followers: 377,
    followings: 201,
    bio: 'Student | Travel | Photography',
    posts: 34,
  },
  {
    username: 'saurabh_node',
    name: 'Saurabh Mishra',
    photo: 'https://i.pravatar.cc/300?img=60',
    email: 'saurabh.mishra@example.com',
    followers: 145,
    followings: 112,
    bio: 'Backend developer | Node.js | MongoDB',
    posts: 20,
  },
];

module.exports = { data: sampleUsers };
